[package]
name = "bufsize"
version = "0.0.0" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>", "Jeremy Fitzhardinge <jeremy@goop.org>"]
edition = "2018"

[dependencies]
bytes = "0.4"

[features]
i128 = ["bytes/i128"]
